### ISSUE TITLE
[1.20.1] Falling trees not working

### ISSUE THREAD

**Issue by MrKashew** [PandaDap2006/Pandas-Falling-Trees#1]
I tried to run this mod on 1.20.1 and the dependency would not recognize cloth-config-10.0.96-forge being present properly. I removed dependency requirement from mods.toml and was able to play, trees won't chop properly for me however. Nothing in logs on this, let me know if more details are necessary to reproduce

**Comment by PandaDap2006** [comment]
First you need cloth config 11.0.99 for 1.20 and 1.20.1, 10.0.96 is for 1.19.4.
And second i made a mistake when setting the modid for the dependency in the mods.toml file, i will make an update as fast as possible.

**Comment by PandaDap2006** [comment]
Every thing should be fixed now, hope you like it.

**Comment by MrKashew** [comment]
Thanks a bunch works like a charm!
