### ISSUE TITLE
[SUGGESTION]-[FIX] Tree falling time calculations

### ISSUE THREAD

**Issue by Wanderer70** [PandaDap2006/Pandas-Falling-Trees#12]
Currently, giant trees (like redwoods from Biomes O' Plenty) fall a bit too fast after being chopped down.
Implementing a calculation system based on tree's size would be great!

**Comment by Camawama** [comment]
https://github.com/PandaDap2006/Pandas-Falling-Trees/issues/25#issue-1831869741

**Comment by PandaDap2006** [comment]
Added something that should work in the latest version.
