### ISSUE TITLE
[SUGGESTION]-[FIX] 'Allow single block mining' keybind and restrictions

### ISSUE THREAD

**Issue by Wanderer70** [PandaDap2006/Pandas-Falling-Trees#13]
Adding a keybind to 'Allow single block mining' would resolve incompatibilities with other mods/actions that require players to use SHIFT. By pressing the keybind, a message appears above the inventory which indicates whether single block mining has been toggled.

In addition to that, there should be some kind of system that forbids certain/chosen trees from **ever** being chopped down by breaking a single block. Some players like making tree bases (in giant trees, presumably) and being sure that their base won't be destroyed by a griefer with a single click would be really reassuring. A command could be used to make certain trees behave like in vanilla. Something like: /pft maketreevanilla radius=5    would make any tree in a 5 block radius behave like in vanilla.

**Comment by PandaDap2006** [comment]
Allow single block mining keybind is already made for the next upcoming version, but as of now there is not indicator for single block mining.

Your second suggestion might not be so easy to implement but i might look into it in the future.

**Comment by PandaDap2006** [comment]
Im closing this issue because most has been added but i will remember to think about something to make tree bases work with the mod.
