### ISSUE TITLE
Support for Cactus & Bamboo

### ISSUE THREAD

**Issue by WenXin20** [PandaDap2006/Pandas-Falling-Trees#19]
Currently if these two blocks are added to the config, it is not detected unless there are leaf blocks connected. 

If added to both leaves and logs detection, the player is kicked from the server when a tree is broken, with nothing in the logs.

**Comment by PandaDap2006** [comment]
my code can only detect trees if it contains a leaves block, but i will add support for these in the future.

**Comment by WenXin20** [comment]
Thanks, sounds good!
