### ISSUE TITLE
[INCOMPATABLE] Does not work with multi mine

### ISSUE THREAD

**Issue by WASTER92** [PandaDap2006/Pandas-Falling-Trees#20]
Hi, first time posting here.
Noticed a collision with this falling tree mod and multi mine. Its playable and all but it breaks just one block and still takes the time of the whole tree. the tree never falls. 
Its not a big deal but I feel like it would be nice to be able to work together with a friend on the big trees to make it go faster.. I hope there is a way to make a "fix" for it. Maybe multi mine should be doing the "fix" i dont know.
Thanks for your time.
:)

**Comment by PandaDap2006** [comment]
i will see if i can add compatibility for future versions
