### ISSUE TITLE
Trees not falling at all in survival

### ISSUE THREAD

**Issue by Stoutscientist** [PandaDap2006/Pandas-Falling-Trees#22]
I have a modpack with around 200 mods and whenever I try to chop down a tree, the mining slows but it doesn't fall, but for some reason it does in creative? Config seems fine.

**Comment by PandaDap2006** [comment]
What Minecraft and mod version are you using.

**Comment by Stoutscientist** [comment]
1.19.4 and "1.19.3-1.20.1 0.5.3-beta"

**Comment by PandaDap2006** [comment]
i will have to look into this.

**Comment by Stoutscientist** [comment]
Alright thanks! I'm not sure if it could be an incompatibility with another mod?

**Comment by bipsydev** [comment]
I think this is happening to me sometimes with partially-cut down trees from Terraqueous, are you running that mod as well?

**Comment by Stoutscientist** [comment]
Interesting, I don't think I'm using that mod. Kind of weird..
