### ISSUE TITLE
[BUG] [1.20.1 FORGE] Trees are not falling

### ISSUE THREAD

**Issue by Camawama** [PandaDap2006/Pandas-Falling-Trees#23]
I started the development of CamaCraft (my modpack) for 1.20.1. Your mod was working perfectly fine but then I had to update the Forge Version so another mod would work and trees no longer fall. They take a long time to mine but then they don't fall down. It is not working in creative either. 

I forgot what version of Forge I was on but I do have the current version: 1.20.1-**47.1.3**

If you need the modpack, I can send a list of the mods. I am developing on Modrinth and don't have the pack finished yet.

**Comment by Camawama** [comment]
This just in! After waiting for 5 minutes, it randomly fell.

Turns out, the world is lagging extremely bad? It was a brand new world though. Everything was working before the tree was cut down.

**Comment by PandaDap2006** [comment]
i dont know why this is happening but i will look into it, does it still take 5 minutes for the tree to start falling for you.

**Comment by Camawama** [comment]
Yes, it seems the trees are not falling, the world starts to lag, and then they fall after a while. I am trying to do some more testing to figure out if it's a mod conflict.

**Comment by PandaDap2006** [comment]
Seems i cant reproduce this issue.
