### ISSUE TITLE
[SUGGESTION] Make larger trees fall slower

### ISSUE THREAD

**Issue by Camawama** [PandaDap2006/Pandas-Falling-Trees#25]
Similar to this video:

https://github.com/PandaDap2006/Pandas-Falling-Trees/assets/43620900/98cac8e1-0c28-4bdf-8765-56d354599ccf

**Comment by PandaDap2006** [comment]
Im planning on adding this for when i make the falling animation overhaul.

**Comment by Camawama** [comment]
> Im planning on adding this for when i make the falling animation overhaul.

I'm excited and cannot wait!

**Comment by PandaDap2006** [comment]
This is added in the latest version.
