### ISSUE TITLE
Chopping placed wood logs

### ISSUE THREAD

**Issue by ManWithSack** [PandaDap2006/Pandas-Falling-Trees#27]
So I'm trying to build a giant jungle tree but when I want to break a log it's making it take a very long time to break 1 log.

**Comment by PandaDap2006** [comment]
Sorry about this, im planning on fixing this for future updates.

**Comment by PandaDap2006** [comment]
This should be gone because i removed the feature from the latest version.

**Comment by tillasiren** [comment]
I have noticed similar issues without the build being particularly large.

![Image](https://github.com/user-attachments/assets/2e566426-5cdb-4c1b-97ec-8e8588ed6fb4)
for example the one under the bricks chops MUCH faster than the block to its right which seems to be acting as if its a tree
