### ISSUE TITLE
[Bug / Feature Request] Diagonal trees such as acacia

### ISSUE THREAD

**Issue by MrKashew** [PandaDap2006/Pandas-Falling-Trees#3]
It seems trees like these ones are currently not supported (cuts the middle section down, then individual pieces act like trees themself)
![2023-06-27_00 41 50](https://github.com/PandaDap2006/Pandas-Falling-Trees/assets/53996665/dd7f2ca8-0f56-4c4f-b525-8feabdd7b918)

**Comment by PandaDap2006** [comment]
im closed to finishing my tree detection revamping, so hope fully that will be fixed there, but may i ask what mods are you using

**Comment by MrKashew** [comment]
tested on the new version - it's fixed!
