### ISSUE TITLE
Severe FPS drops with Better End trees

### ISSUE THREAD

**Issue by kyber-6** [PandaDap2006/Pandas-Falling-Trees#34]
I know for sure this is happening with the Tenanea and Helix trees from Better End, I have not tested with any other trees.

Video demonstration: https://i.imgur.com/qZr431Q.mp4

**Comment by PandaDap2006** [comment]
Does your modpack have the mod Jade, if so i think i know the issue.

**Comment by kyber-6** [comment]
Yes it does.

**Comment by PandaDap2006** [comment]
Then i think the issue might be because when you look at a log, jade shows how many logs will be dropped, i will try and make a fix for the upcoming update.

**Comment by kyber-6** [comment]
Thank you!

**Comment by PandaDap2006** [comment]
I was not able to make a fix for the latest update but if you don't mind the jade compatibility being gone then you can disable it in the config.

**Comment by PandaDap2006** [comment]
Im closing this issue because there has been no response.
