### ISSUE TITLE
[BUG] Compatability with HT's TreeChop

### ISSUE THREAD

**Issue by Camawama** [PandaDap2006/Pandas-Falling-Trees#37]
HT's TreeChop makes it so the player can slowly chop a tree until it breaks. Your mod makes the tree fall after breaking.

Having the two work together would be one step closer to a realistic tree chopping mechanic and I would love to see it work!

I want to slowly chop the bottom of a tree and then (at a certain point) have the tree fall over. 😄 

Currently, with both installed, it only has your mechanics and ignores HT's TreeChop.

**Comment by hammertater** [comment]
If interested @PandaDap2006, I think compatibility should be pretty simple by adding a listener to TreeChop's `AFTER_CHOP` event, checking for `felled == true`. Then check `chopData` for the tree's blocks. See https://github.com/hammertater/treechop/blob/main/fabric/src/main/java/ht/treechop/api/TreeChopEvents.java

It's possible TreeChop's chopped_log blocks would have some rendering issues. I'm happy to help, either by extending the API as needed or by sending a pull request.

**Comment by PandaDap2006** [comment]
Thanks @hammertater for letting me know and for offering your assistance with this, i will reach out if there seems to be any issues.

**Comment by PandaDap2006** [comment]
Accidentally closed the issue, sorry.

**Comment by PandaDap2006** [comment]
Hey @hammertater im currently trying to make compatibility with the mod but `chopData` doesn't have a method or variable for getting the blocks of the tree, it would be great if you could extend the API so it would be possible, you can contact me on discord if you find it necessary, my tag is @thepandaoliver.

**Comment by hammertater** [comment]
Ahh sorry, I made some extensions to the API but forgot that I haven't released them yet. I'll let ya know when it's ready

**Comment by PandaDap2006** [comment]
Sounds great, thanks.

**Comment by Camawama** [comment]
This is very exciting, can't wait!

**Comment by GulliUlli** [comment]
anything new? :D i found the mod few minues ago and im allready using treechop^^ i would be really cool, to use both together

**Comment by PandaDap2006** [comment]
@GulliUlli Sadly treechop have not been updated yet.

**Comment by Camawama** [comment]
It looks like something happened 5 days ago https://github.com/hammertater/treechop/issues/233

**Comment by hammertater** [comment]
Hey folks, sorry for how long it’s taking. I have made the changes but haven’t posted an updated version yet. I’ll try to get it up tomorrow-ish

**Comment by hammertater** [comment]
Sorry for the wait! As of 0.18.5 (only for Minecraft 1.19.2 right now) there's a new a `getTree` method in the `ChopData` class. That'll return a `TreeData` object that has all of the positions for logs. If you need the leaves as well, TreeData's `forEachLeaves` is faster than `streamLeaves`, but make sure you read all of the logs first or it might not find all of the leaves. Sorry for the jankiness.

**Comment by PandaDap2006** [comment]
Thanks so much i might take a look at later today.

**Comment by GulliUlli** [comment]
uuh sounds like progress in that case? :P

**Comment by Camawama** [comment]
I see progress 👀

**Comment by PandaDap2006** [comment]
Yep working on it.

**Comment by PandaDap2006** [comment]
Support for HT's TreeChop has officially been added, the released can only be downloaded on CurseForge and Github, Modrinth will be released at a later time.

**Comment by Camawama** [comment]
WooHoo!!!

**Comment by Camawama** [comment]
Now we just need compatibility with MultiMine mod

**Comment by DaeTheDragon** [comment]
Heya! 
When chopping down a tree with HT's Tree Chop, the tree doesn't fall at the point the cut was made, instead it destroys the block above.
this isn't mechanically problematic, it's just visually unappealing - still, is there any way this could be fixed?

https://github.com/PandaDap2006/Pandas-Falling-Trees/assets/80906771/8ad130a3-b2c4-43b9-ab89-2f04a3a43271

I'm using the latest versions of both mods on Neoforge 1.20.1

**Comment by DaeTheDerg** [comment]
Hiya! are we likely to get compatibility back in future?
as mentioned it's no longer working, HT seems to overwrite the function of this mod, causing it to not do anything at all anymore :[
