### ISSUE TITLE
[BUG] Treee falling sound is not played positionally

### ISSUE THREAD

**Issue by Camawama** [PandaDap2006/Pandas-Falling-Trees#38]
If a tree falls in the forest and nobody is around, it doesn't make a sound (at least that's what they say)....but currently, if I chop a tree in a forest and fly away very quickly, I still hear the sound very loud.

**Comment by PandaDap2006** [comment]
Thanks for letting me know, i will fix this issue when i have time.

**Comment by Beleggrodion** [comment]
I and some friends play on multiplayer (via open in lan) and had a similar issue with the sound. I can chop wood miles away or in the nether, all on the server hear the sound.

**Comment by Camawama** [comment]
Oh, that was the same issue I had when importing music discs. They needed to be MONO in order for positioning to work properly. Glad to see you got it solved!
