### ISSUE TITLE
[Bug] Tree falling sound on original block

### ISSUE THREAD

**Issue by Zano1999** [PandaDap2006/Pandas-Falling-Trees#39]
After cutting down a tree, if a block is placed on the block of land where the tree stood before it returns to grass and is then destroyed, the sound of the tree falling will be played.

**Comment by PandaDap2006** [comment]
I will try and see if i can reproduce it.

**Comment by Camawama** [comment]
Same thing happens to me. The sound is played if a log is placed near where the tree once stood.

https://www.youtube.com/watch?v=TLv0SY6MP9k

**Comment by Camawama** [comment]
Also was randomly getting this error and kicked from the server when other's would chop logs.

(Internal Exception: java.lang.IndexOutOfBoundsException: readerIndex(31) + length(1) exceeds writerIndex(31): PooledUnsafeDirectByteBuf(ridx: 31, widx: 31, cap: 31)

**Comment by MrKashew** [comment]
happens to me too

**Comment by PandaDap2006** [comment]
Should be fixed in the latest version, if not then please open this issue again.
