### ISSUE TITLE
[1.20.1] Compatibility with Wood block and mixed log / wood block combinations

### ISSUE THREAD

**Issue by MrKashew** [PandaDap2006/Pandas-Falling-Trees#4]
apologies for all the tix recently
mods such as Regions Unexplored create trees with Wood blocks (log with texture on all sides)
and sometimes a mix of different wood types and block types, including stripped wood
is there any way to support these
example of a mixed wood type tree
![image](https://github.com/PandaDap2006/Pandas-Falling-Trees/assets/53996665/84c1fbbd-9b3c-4729-b0ec-2bda7e1f899c)

**Comment by PandaDap2006** [comment]
In the new update to the mod, i made it so logs and leaves are identified by the logs and leaves block tag, so as long as the mod creator added the logs and leaves to the logs and leaves block tag, then it should work. I tested the mod with Regions Unexplored my self and, it worked. is this an issue or a question?

**Comment by MrKashew** [comment]
Sorry I kinda clumped together a few questions
Issue - trees made of this (oak wood) block would not cut down properly, perhaps Wood type can be added or also bring back whitelist feature in addition, meaning modpackers can tune this themselves? I see whitelist has been removed in favor for only blacklisting
![image](https://github.com/PandaDap2006/Pandas-Falling-Trees/assets/53996665/6d6101bd-f73d-44d4-8308-fe7d4f8cb594)
Question was - if mixed types would work together, which seems to be answered as yes as long as its log tag

**Comment by PandaDap2006** [comment]
thank you, i will add the whitelist back and add a tag whitelist.
