### ISSUE TITLE
Crashing because Tree type is null in the entity

### ISSUE THREAD

**Issue by Ceifeire** [PandaDap2006/Pandas-Falling-Trees#42]
Hey im having occasional crashes. So far it occurs when i cut a tree down while another is falling.

MC Version: 1.19.2
Mod Version: fallingtrees-.07-beta-forge
Modpack attached below

Crash report: https://pastebin.com/f0wnWPuJ
[1.19.2_Build_server.zip](https://github.com/PandaDap2006/Pandas-Falling-Trees/files/13420734/1.19.2_Build_server.zip)

**Comment by PandaDap2006** [comment]
Sorry about this, i think i ran into this issue recently in development and think i fixed it but i will take a look and see if i can figure out why it happens.

**Comment by Ceifeire** [comment]
After playing with it some more it does not appear to be tetra compatible either. At least if you change from a basic axe to any other type of axe it would let you make

**Comment by PandaDap2006** [comment]
Has been fixed
