### ISSUE TITLE
[1.19.2] Chorus trees do not drop chorus fruits.

### ISSUE THREAD

**Issue by Nemirel345** [PandaDap2006/Pandas-Falling-Trees#55]
When chopping down a chorus tree, you get the chorus flowers items equal to the ones that grew on the tree, but none of the chorus fruits.

It should give a random amount related to the amount of chorus plant blocks in that tree.

**Comment by PandaDap2006** [comment]
Thanks for the report, I will get that fixed in the next version.

**Comment by PandaDap2006** [comment]
This issue has been fixed
