### ISSUE TITLE
pandalib 0.2 incompatibility(?)

### ISSUE THREAD

**Issue by KingOfCaves** [PandaDap2006/Pandas-Falling-Trees#56]
Encountered an issue after updating some of my mods with Prism's built checker (including pandalib). Falling Trees works with 0.1 but get an error loading with 0.2.

Minecraft 1.20.1
Forge 47.2.21

![javaw_xJ8rgBq0ws](https://github.com/PandaDap2006/Pandas-Falling-Trees/assets/37917347/57b8bc62-5a2a-4885-a789-155f0e9ffef0)

latest.log
https://hastebin.com/share/oxiqetozew.markdown

crash.log
https://hastebin.com/share/ikugihasul.php

**Comment by PandaDap2006** [comment]
This has been fixed, update falling trees to 0.11
