### ISSUE TITLE
Incompatibility with Valkyrien Skies 2

### ISSUE THREAD

**Issue by RowanSkie** [PandaDap2006/Pandas-Falling-Trees#57]
https://mclo.gs/GhUb0ZO

Running this mod alongside Valkyrien Skies 2 causes the game to CTD. Attached is a log that supports it.

**Comment by PandaDap2006** [comment]
This issue might not be Valkyrien skies, it might have been PandaLib, i just released an update Falling trees that fixes this, update to 0.11.

**Comment by RowanSkie** [comment]
Update works, no longer CTDs.
