### ISSUE TITLE
[1.19.3] MC crashes at startup

### ISSUE THREAD

**Issue by Cape-City** [PandaDap2006/Pandas-Falling-Trees#6]
Hi,

the mod is absolutly perfect for my big modpack, but actually MC directly crashes at startup:

[crash-2023-07-04_18.04.39-client.txt](https://github.com/PandaDap2006/Pandas-Falling-Trees/files/11951032/crash-2023-07-04_18.04.39-client.txt)

[latest.log](https://github.com/PandaDap2006/Pandas-Falling-Trees/files/11951037/latest.log)

**Comment by PandaDap2006** [comment]
i will fix that fast, sorry for the mistake.

**Comment by PandaDap2006** [comment]
This should be fixed now, enjoy.

**Comment by Cape-City** [comment]
Works perfect, now i have to find a way to get it work with another mod together.
