### ISSUE TITLE
No Config

### ISSUE THREAD

**Issue by QwertRvg** [PandaDap2006/Pandas-Falling-Trees#60]
Minecraft 1.20.1
Forge 47.2.0
Falling Trees 0.11

No config file gets generated, so no settings can be changed.

**Comment by PandaDap2006** [comment]
Can you send the latest log, i cant identify the problem without it.

**Comment by QwertRvg** [comment]
oh, I just checked again
there now is a config file, dont know what changed though

its still not accessible through the Forge Config Screens mod tho

**Comment by PandaDap2006** [comment]
Its because i switch to using my own config api, it does not have a config screen yet so its currently in development.

**Comment by Rhett008** [comment]
> Its because i switch to using my own config api, it does not have a config screen yet so its currently in development.

Any chance we may know when we can get a config screen released?

**Comment by PandaDap2006** [comment]
Its still hard for me to say when its ready. All i can say is development is going well at the moment.
