### ISSUE TITLE
Game CTD when chppping down tree

### ISSUE THREAD

**Issue by Svodantyrie** [PandaDap2006/Pandas-Falling-Trees#64]
The game crashes to desktop everytime I chop down a tree. I'm not very good at tracking down the actual issue and how to solve it, so I've attached the crashlog below. I'm also using a few other mods, but I can't see why there should be any incompatibilities on that end. See below for details.

Modloader: Forge

Mods:
Quad
Advanced Finders
Architectury API
Camps. Castles. Carriages.
Cristel Lib
Extended Workbench Reborn
ForgeEndertech
GeoSmelt
Glitchcore
JJThunder King of the Hills
Macaw's Doors
More Beautiful Torches
More Chest Variants
Terrablender
Towns and Towers
Xaero's Minimap

Crashlog:
https://pastebin.com/eL8MRWpi

**Comment by Svodantyrie** [comment]
I forgot to mention one mod I'm also using, which is Biomes O' Plenty.

**Comment by PandaDap2006** [comment]
The cause of the issue is Optifine sadly, its not compatible.

**Comment by Svodantyrie** [comment]
I see, that's too bad. Oh well, wat do? Thanks!
