### ISSUE TITLE
Bamboo, Cactus, Chorus Trees, and Mushrooms Ignore Required Tool Parameter + Fall When Standing Up

### ISSUE THREAD

**Issue by Rhett008** [PandaDap2006/Pandas-Falling-Trees#65]
Minecraft Version:
1.20.1

Mod Loader/Version:
Fabric 0.15.7

Mod versions:
Falling Trees 0.11
PandaLib: 0.2

Issue:
Bamboo, Cactus, Chorus Trees and Mushrooms do not respect the  "onlyFallWithRequiredTool" parameter.
When "onlyFallWithRequiredTool" is set to true, normal trees only fall when using minecraft:axes (by default).

The 4 above-mentioned "tree" types fall when punched with your hand or any other tool that is not a weapon.

Additionally, they also fall when:
 - The player is standing or crouching, ignoring the norm,
 - Blocks on the top of the stack fall when they are broken, unlike normal trees.

This makes mining individual blocks a pain, having to wait to go through the animation whenever the required tool is not used.

**Comment by PandaDap2006** [comment]
This has been added in 0.12
