### ISSUE TITLE
The latest version of Falling Trees tells me it's incompatible with HT's Tree Chop version 0.18.8 despite me using 0.19.0

### ISSUE THREAD

**Issue by AngelsLikeChopSuey** [PandaDap2006/Pandas-Falling-Trees#78]
The latest version of Falling Trees tells me it's incompatible with HT's Tree Chop version 0.18.8 despite me using 0.19.0 whenever I start up the game 
![image](https://github.com/PandaDap2006/Pandas-Falling-Trees/assets/147362707/e64ad24e-d9be-4768-9c83-cddf7b929b6c)
![image](https://github.com/PandaDap2006/Pandas-Falling-Trees/assets/147362707/e8cbf59a-bd74-41e6-aa2a-0a66ca42bdd7)

**Comment by PandaDap2006** [comment]
This issue has been fixed
