### ISSUE TITLE
[1.20.1] Enormous trees will register valid for chop down (whitelisted blocks)

### ISSUE THREAD

**Issue by MrKashew** [PandaDap2006/Pandas-Falling-Trees#8]
Seems the algorithm is well made as it doesn't crash game - game stalls for a few minutes
Here is the result of mushrooms being considered trees - not sure if this itself applies to extremely large trees
If so maybe can config a limit the max size allowed for chopping and give user warning? Not sure entirely but could be worth investigating if this issue is valid
![2023-07-07_01 49 54](https://github.com/PandaDap2006/Pandas-Falling-Trees/assets/53996665/bfe8de7d-11e0-4db0-a7a7-609461b8e136)
![2023-07-07_01 47 21](https://github.com/PandaDap2006/Pandas-Falling-Trees/assets/53996665/965fca9c-43be-4db1-933f-9bf6640f7e2f)

**Comment by MrKashew** [comment]
I feel this shouldn't be an issue once #7 chopping taking longer based on blocks is implemented as user will realize what they're about to do

**Comment by PandaDap2006** [comment]
oh i did not think if this being an issue, sorry i will add an limiter for the next update.
Also you can join my discord if you want to stay updated on my mods.
